image: rust:latest

variables:
  DATABASE_URL: "sqlite:discord_bot.db"

default:
  cache:
    - key: $CI_COMMIT_REF_SLUG
      paths:
        - .cargo/bin/
        - target

stages:
  - check
  #- build
  #- deploy

before_script:
  - apt update -qy
  - apt install cmake sqlite3 aria2 -qy
  - mkdir -p ~/.cargo/bin
  - aria2c -d ~/.cargo/bin "https://github.com/cargo-bins/cargo-binstall/releases/latest/download//cargo-binstall-x86_64-unknown-linux-gnu.full.tgz"
  - ls -Al --color
  - ls -Al --color ~/.cargo/bin
  - tar -xf ~/.cargo/bin/cargo-binstall-x86_64-unknown-linux-gnu.full.tgz -C ~/.cargo/bin
  - cargo binstall -y sqlx-cli
  - cargo sqlx database setup

format:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    #- if: $CI_COMMIT_TAG
  variables:
    RUSTFLAGS: "-Dwarnings"
  script:
    - cargo fmt --check

clippy:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    #- if: $CI_COMMIT_TAG
  variables:
    RUSTFLAGS: "-Dwarnings"
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features

features:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    #- if: $CI_COMMIT_TAG
  variables:
    RUSTFLAGS: "-Dwarnings"
  script:
    - cargo binstall -y cargo-all-features
    - cargo check-all-features

#build:
#  stage: build
#  rules:
#    - if: $CI_COMMIT_TAG
#  scripts:
#    - cargo build --release
