image: rust:latest

variables:
  DATABASE_URL: "sqlite:discord_bot.db"

default:
  cache:
    - key: $CI_COMMIT_REF_SLUG
      paths:
        - .cargo/bin/
        - target

stages:
  - check
  #- build
  #- deploy

before_script:
  - apt update -qy
  - apt install cmake -qy
  - cargo install cargo-binstall
  - cargo binstall -y sqlx-cli
  - cargo sqlx database setup

format:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    #- if: $CI_COMMIT_TAG
  variables:
    RUSTFLAGS: "-Dwarnings"
  script:
    - cargo fmt --check

clippy:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    #- if: $CI_COMMIT_TAG
  variables:
    RUSTFLAGS: "-Dwarnings"
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features

features:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    #- if: $CI_COMMIT_TAG
  variables:
    RUSTFLAGS: "-Dwarnings"
  script:
    - cargo binstall -y cargo-all-features
    - cargo check-all-features

#build:
#  stage: build
#  rules:
#    - if: $CI_COMMIT_TAG
#  scripts:
#    - cargo build --release
