[package]
name = "discord-bot"
description = "Discord bot for playing music in VC but can make other things as well"
version = "2.2.0"
edition = "2021"
license-file = "LICENSE"
repository = "https://gitlab.com/Erenoit/discord-bot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
colored = "2.0"
clap = { version = "4.1", features = ["derive"], optional = true }
directories = "5.0"
dotenv = { version = "0.15", optional = true }
reqwest = "0.11"
json = "0.12"
poise = "0.5"
rand = "0.8"
serde = "1.0"
serenity = { version = "0.11", default-features = false, features = [
    "client",
    "collector",
    "gateway",
    "rustls_backend",
    "model",
    "voice",
] }
songbird = { version = "0.3", features = ["yt-dlp"], optional = true }
sqlx = { version = "0.6", features = [
    "macros",
    "migrate",
    "runtime-tokio-rustls",
    "sqlite",
], optional = true }
taplo = { version = "0.12", optional = true }
tokio = { version = "1.26", features = [
    "macros",
    "rt-multi-thread",
    "parking_lot",
] }

[build-dependencies]
clap = { version = "4.1", features = ["derive"], optional = true }
clap_complete = { version = "4.1", optional = true }

[profile.release]
opt-level = 3
lto = true
panic = 'abort'
overflow-checks = false

[features]
default = ["cmd", "config_file", "database", "dotenv", "music", "spotify"]
cmd = ["dep:clap", "dep:clap_complete"]
config_file = ["dep:taplo"]
database = ["dep:sqlx", "music"]
dotenv = ["dep:dotenv"]
music = ["dep:songbird"]
spotify = ["music"]
