[package]
name = "discord-bot"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
colored = "2.0"
directories = "4.0"
dotenv = "0.15"
reqwest = "0.11"
json = "0.12"
serde = "1.0"
songbird = "0.3"
poise = "0.5"
rand = "0.8"
rocksdb = "0.19"
serenity = { version = "0.11", default-features = false, features = ["client", "collector", "gateway", "rustls_backend", "model", "voice"] }
taplo = "0.12"
tokio = { version = "1.23", features = ["macros", "rt-multi-thread", "parking_lot"] }

[profile.release]
opt-level = 3
lto = true
panic = 'abort'
overflow-checks = false

