[general]
token = "YOUR_BOT_TOKEN"
prefix = "-"
auto_register_commands = true
vc_auto_change = false

[youtube]
search_count = 5
age_restricted = false

[spotify]
enable = false
#client_id = "SPOTIFY_CLIENT_ID"
#client_secret = "SPOTIFY_CLIENT_SECRET"

[database]
enable = true
#location = ""

