[general]
token = "YOUR_BOT_TOKEN"
prefix = "-"
auto_register_commands = true
vc_auto_change = false

[message]
always_embed = false
random_embed_colors = false
success_color = 0x00FF00
normal_color = 0x0000FF
error_color = 0xFF0000
interaction_time_limit = 30

[youtube]
search_count = 5
age_restricted = false

[spotify]
enable = false
#client_id = "SPOTIFY_CLIENT_ID"
#client_secret = "SPOTIFY_CLIENT_SECRET"

[database]
enable = true
#location = ""
